(function(cjs, an) {
    var p;
    var lib = {};
    var ss = {};
    var img = {};
    var rect;
    lib.ssMetadata = [];

    function mc_symbol_clone() {
        var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
        clone.gotoAndStop(this.currentFrame);
        clone.paused = this.paused;
        clone.framerate = this.framerate;
        return clone;
    }

    function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
        var prototype = cjs.extend(symbol, cjs.MovieClip);
        prototype.clone = mc_symbol_clone;
        prototype.nominalBounds = nominalBounds;
        prototype.frameBounds = frameBounds;
        return prototype;
    }
    (lib.sound = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.frame_0 = function() { this.stop(); }
        this.frame_1 = function() { playSound("bell"); }
        this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = null;
    p.frameBounds = [rect, rect];
    (lib.onlinestopwatchcom = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#FFFFFF").s().p("AAdAdIAAgjIgBgIQgBgDgDgBQgCgCgDAAQgGAAgEAEQgEAEAAAJIAAAgIgJAAIAAgkQAAgGgCgDQgCgEgGAAQgEAAgEACQgDADgCAEQgBAEAAAHIAAAdIgKAAIAAg4IAJAAIAAAIQADgEAEgDQAFgCAFAAQAGAAAEADQAEACACAFQAGgKALAAQAIAAAFAFQAEAEABAKIAAAmg");
        this.shape.setTransform(272.7, 10.4);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.f("#FFFFFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_1.setTransform(264, 10.5);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.f("#FFFFFF").s().p("AgRAWQgHgHAAgPQAAgIADgHQADgHAGgEQAHgDAGAAQAJAAAGAFQAGAFACAIIgKABQgBgFgDgDQgEgDgFAAQgGAAgEAFQgFAGAAAKQAAAMAEAEQAFAGAGAAQAGAAADgEQAEgDABgHIAKABQgCAJgGAHQgHAFgJAAQgLAAgHgIg");
        this.shape_2.setTransform(257.4, 10.5);
        this.shape_3 = new cjs.Shape();
        this.shape_3.graphics.f("#FFFFFF").s().p("AgEAFIAAgKIAJAAIAAAKg");
        this.shape_3.setTransform(252, 12.8);
        this.shape_4 = new cjs.Shape();
        this.shape_4.graphics.f("#FFFFFF").s().p("AAOAnIAAgkQAAgGgEgDQgCgEgHAAQgDAAgDADQgEACgCAEQgCACABAHIAAAfIgKAAIAAhNIAKAAIAAAcQAGgIAKAAQAGAAAFACQAEADACAEQACAFAAAHIAAAkg");
        this.shape_4.setTransform(246.4, 9.4);
        this.shape_5 = new cjs.Shape();
        this.shape_5.graphics.f("#FFFFFF").s().p("AgRAWQgHgHAAgPQAAgIADgHQADgHAGgEQAHgDAGAAQAJAAAGAFQAGAFACAIIgKABQgBgFgDgDQgEgDgFAAQgGAAgEAFQgFAGAAAKQAAAMAEAEQAFAGAGAAQAGAAADgEQAEgDABgHIAKABQgCAJgGAHQgHAFgJAAQgLAAgHgIg");
        this.shape_5.setTransform(239.8, 10.5);
        this.shape_6 = new cjs.Shape();
        this.shape_6.graphics.f("#FFFFFF").s().p("AAAAlQgDgCgCgDQgBgCAAgJIAAggIgHAAIAAgHIAHAAIAAgOIAIgGIAAAUIAKAAIAAAHIgKAAIAAAhIABAFIACACIADABIAEAAIACAIIgHABQgGAAgBgCg");
        this.shape_6.setTransform(234.4, 9.6);
        this.shape_7 = new cjs.Shape();
        this.shape_7.graphics.f("#FFFFFF").s().p("AgUAZQgFgFAAgGQAAgEACgEIAFgGIAHgCIAIgBIAQgEIAAgCQAAgGgCgDQgEgDgHAAQgGAAgDADQgEACgBAGIgKgBQACgHADgDQADgEAFgCQAGgCAGAAQAHAAAFACQAFACACACIADAHIAAAIIAAANIABARIACAGIgKAAIgCgGQgFAEgFACQgEACgGAAQgJAAgFgFgAgBAEIgJACIgEACIgBAFQAAAEADACQADADAGAAQAEAAAEgCQAFgDACgEQABgDAAgGIAAgEQgFACgJACg");
        this.shape_7.setTransform(228.7, 10.5);
        this.shape_8 = new cjs.Shape();
        this.shape_8.graphics.f("#FFFFFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAJggIAJAAIAJAgIADALIADgLIAJggIAKAAIgSA3g");
        this.shape_8.setTransform(220.7, 10.5);
        this.shape_9 = new cjs.Shape();
        this.shape_9.graphics.f("#FFFFFF").s().p("AgYAoIAAhOIAJAAIAAAIQADgFAEgCQAEgCAEAAQAIAAAFAEQAGADADAHQADAHAAAIQAAAJgEAGQgDAHgGAEQgGAEgGAAQgEAAgEgDQgEgCgCgDIAAAcgAgKgaQgFAGAAALQAAAKAEAFQAFAGAGAAQAFAAAFgGQAFgFAAgLQAAgLgFgFQgEgGgGAAQgGAAgEAGg");
        this.shape_9.setTransform(212.9, 11.5);
        this.shape_10 = new cjs.Shape();
        this.shape_10.graphics.f("#FFFFFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_10.setTransform(205.6, 10.5);
        this.shape_11 = new cjs.Shape();
        this.shape_11.graphics.f("#FFFFFF").s().p("AAAAlQgEgCgBgDQgBgCAAgJIAAggIgHAAIAAgHIAHAAIAAgOIAIgGIAAAUIAKAAIAAAHIgKAAIAAAhIABAFIACACIADABIAEAAIACAIIgHABQgGAAgBgCg");
        this.shape_11.setTransform(200.1, 9.6);
        this.shape_12 = new cjs.Shape();
        this.shape_12.graphics.f("#FFFFFF").s().p("AgPAZQgGgEgCgKIAKgBQABAGADADQAEADAFAAQAHAAADgDQAEgDAAgDQAAgDgDgCIgKgDIgOgFQgEgBgCgDQgCgEAAgEQAAgEACgDIAEgGIAGgCQAEgCAFAAQAFAAAGACQAFACACAEQACADABAFIgJACQgBgFgDgCQgDgDgFAAQgGAAgDADQgDABAAAEIABADIAEACIAIADIAOAEQAEABACAEQADADAAAEQAAAGgDAEQgDAEgFACQgGADgGAAQgLAAgFgFg");
        this.shape_12.setTransform(194.7, 10.5);
        this.shape_13 = new cjs.Shape();
        this.shape_13.graphics.f("#FFFFFF").s().p("AgOAFIAAgJIAdAAIAAAJg");
        this.shape_13.setTransform(189.2, 10.5);
        this.shape_14 = new cjs.Shape();
        this.shape_14.graphics.f("#FFFFFF").s().p("AgSAWQgHgHAAgPQAAgNAHgIQAIgIAKAAQAMAAAHAIQAHAIAAANIAAACIgpAAQAAAKAFAFQAFAFAGAAQAFAAAEgDQAEgDACgGIAKABQgCAJgHAFQgGAFgKAAQgMAAgHgIgAgKgRQgEAFgBAIIAfAAQAAgHgDgFQgFgFgHAAQgGAAgFAEg");
        this.shape_14.setTransform(183.3, 10.5);
        this.shape_15 = new cjs.Shape();
        this.shape_15.graphics.f("#FFFFFF").s().p("AAOAdIAAghIgBgJQgCgDgDgCQgCgCgFAAQgFAAgEAEQgFAEABALIAAAeIgKAAIAAg4IAJAAIAAAIQAFgJAMAAQAFAAAEACQAFACABADIAEAHIAAAJIAAAig");
        this.shape_15.setTransform(176.2, 10.4);
        this.shape_16 = new cjs.Shape();
        this.shape_16.graphics.f("#FFFFFF").s().p("AgEAnIAAg4IAJAAIAAA4gAgEgbIAAgLIAJAAIAAALg");
        this.shape_16.setTransform(170.9, 9.4);
        this.shape_17 = new cjs.Shape();
        this.shape_17.graphics.f("#FFFFFF").s().p("AgEAnIAAhNIAJAAIAABNg");
        this.shape_17.setTransform(167.4, 9.4);
        this.shape_18 = new cjs.Shape();
        this.shape_18.graphics.f("#FFFFFF").s().p("AANAdIAAghIgBgJQgBgDgCgCQgEgCgDAAQgFAAgFAEQgEAEgBALIAAAeIgJAAIAAg4IAIAAIAAAIQAHgJAKAAQAGAAAEACQAFACACADIACAHIABAJIAAAig");
        this.shape_18.setTransform(162.2, 10.4);
        this.shape_19 = new cjs.Shape();
        this.shape_19.graphics.f("#FFFFFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_19.setTransform(155.1, 10.5);
        this.shape_20 = new cjs.Shape();
        this.shape_20.graphics.f("#FFFFFF").s().p("AgEAFIAAgKIAKAAIAAAKg");
        this.shape_20.setTransform(149.6, 12.8);
        this.shape_21 = new cjs.Shape();
        this.shape_21.graphics.f("#FFFFFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAKggIAIAAIAJAgIACALIAEgLIAKggIAJAAIgSA3g");
        this.shape_21.setTransform(143, 10.5);
        this.shape_22 = new cjs.Shape();
        this.shape_22.graphics.f("#FFFFFF").s().p("AALAcIgJggIgCgLIgKArIgKAAIgSg3IAKAAIAJAgIADALIADgLIAJggIAJAAIAJAgIADALIADgLIAJggIAKAAIgSA3g");
        this.shape_22.setTransform(134.1, 10.5);
        this.shape_23 = new cjs.Shape();
        this.shape_23.graphics.f("#FFFFFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAKggIAIAAIAJAgIACALIAEgLIAKggIAJAAIgSA3g");
        this.shape_23.setTransform(125.1, 10.5);
        this.shape_24 = new cjs.Shape();
        this.shape_24.graphics.f("#A2DAFF").s().p("AAdAdIAAgjIgBgIQgBgDgDgBQgCgCgDAAQgGAAgEAEQgEAEAAAJIAAAgIgJAAIAAgkQAAgGgCgDQgCgEgGAAQgEAAgEACQgDADgCAEQgBAEAAAHIAAAdIgKAAIAAg4IAJAAIAAAIQADgEAEgDQAFgCAFAAQAGAAAEADQAEACACAFQAGgKALAAQAIAAAFAFQAEAEABAKIAAAmg");
        this.shape_24.setTransform(272.7, 10.4);
        this.shape_25 = new cjs.Shape();
        this.shape_25.graphics.f("#A2DAFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_25.setTransform(264, 10.5);
        this.shape_26 = new cjs.Shape();
        this.shape_26.graphics.f("#A2DAFF").s().p("AgRAWQgHgHAAgPQAAgIADgHQADgHAGgEQAHgDAGAAQAJAAAGAFQAGAFACAIIgKABQgBgFgDgDQgEgDgFAAQgGAAgEAFQgFAGAAAKQAAAMAEAEQAFAGAGAAQAGAAADgEQAEgDABgHIAKABQgCAJgGAHQgHAFgJAAQgLAAgHgIg");
        this.shape_26.setTransform(257.4, 10.5);
        this.shape_27 = new cjs.Shape();
        this.shape_27.graphics.f("#A2DAFF").s().p("AgEAFIAAgKIAJAAIAAAKg");
        this.shape_27.setTransform(252, 12.8);
        this.shape_28 = new cjs.Shape();
        this.shape_28.graphics.f("#A2DAFF").s().p("AAOAnIAAgkQAAgGgEgDQgCgEgHAAQgDAAgDADQgEACgCAEQgCACABAHIAAAfIgKAAIAAhNIAKAAIAAAcQAGgIAKAAQAGAAAFACQAEADACAEQACAFAAAHIAAAkg");
        this.shape_28.setTransform(246.4, 9.4);
        this.shape_29 = new cjs.Shape();
        this.shape_29.graphics.f("#A2DAFF").s().p("AgRAWQgHgHAAgPQAAgIADgHQADgHAGgEQAHgDAGAAQAJAAAGAFQAGAFACAIIgKABQgBgFgDgDQgEgDgFAAQgGAAgEAFQgFAGAAAKQAAAMAEAEQAFAGAGAAQAGAAADgEQAEgDABgHIAKABQgCAJgGAHQgHAFgJAAQgLAAgHgIg");
        this.shape_29.setTransform(239.8, 10.5);
        this.shape_30 = new cjs.Shape();
        this.shape_30.graphics.f("#A2DAFF").s().p("AAAAlQgDgCgCgDQgBgCAAgJIAAggIgHAAIAAgHIAHAAIAAgOIAIgGIAAAUIAKAAIAAAHIgKAAIAAAhIABAFIACACIADABIAEAAIACAIIgHABQgGAAgBgCg");
        this.shape_30.setTransform(234.4, 9.6);
        this.shape_31 = new cjs.Shape();
        this.shape_31.graphics.f("#A2DAFF").s().p("AgUAZQgFgFAAgGQAAgEACgEIAFgGIAHgCIAIgBIAQgEIAAgCQAAgGgCgDQgEgDgHAAQgGAAgDADQgEACgBAGIgKgBQACgHADgDQADgEAFgCQAGgCAGAAQAHAAAFACQAFACACACIADAHIAAAIIAAANIABARIACAGIgKAAIgCgGQgFAEgFACQgEACgGAAQgJAAgFgFgAgBAEIgJACIgEACIgBAFQAAAEADACQADADAGAAQAEAAAEgCQAFgDACgEQABgDAAgGIAAgEQgFACgJACg");
        this.shape_31.setTransform(228.7, 10.5);
        this.shape_32 = new cjs.Shape();
        this.shape_32.graphics.f("#A2DAFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAJggIAJAAIAJAgIADALIADgLIAJggIAKAAIgSA3g");
        this.shape_32.setTransform(220.7, 10.5);
        this.shape_33 = new cjs.Shape();
        this.shape_33.graphics.f("#A2DAFF").s().p("AgYAoIAAhOIAJAAIAAAIQADgFAEgCQAEgCAEAAQAIAAAFAEQAGADADAHQADAHAAAIQAAAJgEAGQgDAHgGAEQgGAEgGAAQgEAAgEgDQgEgCgCgDIAAAcgAgKgaQgFAGAAALQAAAKAEAFQAFAGAGAAQAFAAAFgGQAFgFAAgLQAAgLgFgFQgEgGgGAAQgGAAgEAGg");
        this.shape_33.setTransform(212.9, 11.5);
        this.shape_34 = new cjs.Shape();
        this.shape_34.graphics.f("#A2DAFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_34.setTransform(205.6, 10.5);
        this.shape_35 = new cjs.Shape();
        this.shape_35.graphics.f("#A2DAFF").s().p("AAAAlQgEgCgBgDQgBgCAAgJIAAggIgHAAIAAgHIAHAAIAAgOIAIgGIAAAUIAKAAIAAAHIgKAAIAAAhIABAFIACACIADABIAEAAIACAIIgHABQgGAAgBgCg");
        this.shape_35.setTransform(200.1, 9.6);
        this.shape_36 = new cjs.Shape();
        this.shape_36.graphics.f("#A2DAFF").s().p("AgPAZQgGgEgCgKIAKgBQABAGADADQAEADAFAAQAHAAADgDQAEgDAAgDQAAgDgDgCIgKgDIgOgFQgEgBgCgDQgCgEAAgEQAAgEACgDIAEgGIAGgCQAEgCAFAAQAFAAAGACQAFACACAEQACADABAFIgJACQgBgFgDgCQgDgDgFAAQgGAAgDADQgDABAAAEIABADIAEACIAIADIAOAEQAEABACAEQADADAAAEQAAAGgDAEQgDAEgFACQgGADgGAAQgLAAgFgFg");
        this.shape_36.setTransform(194.7, 10.5);
        this.shape_37 = new cjs.Shape();
        this.shape_37.graphics.f("#A2DAFF").s().p("AgOAFIAAgJIAdAAIAAAJg");
        this.shape_37.setTransform(189.2, 10.5);
        this.shape_38 = new cjs.Shape();
        this.shape_38.graphics.f("#A2DAFF").s().p("AgSAWQgHgHAAgPQAAgNAHgIQAIgIAKAAQAMAAAHAIQAHAIAAANIAAACIgpAAQAAAKAFAFQAFAFAGAAQAFAAAEgDQAEgDACgGIAKABQgCAJgHAFQgGAFgKAAQgMAAgHgIgAgKgRQgEAFgBAIIAfAAQAAgHgDgFQgFgFgHAAQgGAAgFAEg");
        this.shape_38.setTransform(183.3, 10.5);
        this.shape_39 = new cjs.Shape();
        this.shape_39.graphics.f("#A2DAFF").s().p("AAOAdIAAghIgBgJQgCgDgDgCQgCgCgFAAQgFAAgEAEQgFAEABALIAAAeIgKAAIAAg4IAJAAIAAAIQAFgJAMAAQAFAAAEACQAFACABADIAEAHIAAAJIAAAig");
        this.shape_39.setTransform(176.2, 10.4);
        this.shape_40 = new cjs.Shape();
        this.shape_40.graphics.f("#A2DAFF").s().p("AgEAnIAAg4IAJAAIAAA4gAgEgbIAAgLIAJAAIAAALg");
        this.shape_40.setTransform(170.9, 9.4);
        this.shape_41 = new cjs.Shape();
        this.shape_41.graphics.f("#A2DAFF").s().p("AgEAnIAAhNIAJAAIAABNg");
        this.shape_41.setTransform(167.4, 9.4);
        this.shape_42 = new cjs.Shape();
        this.shape_42.graphics.f("#A2DAFF").s().p("AANAdIAAghIgBgJQgBgDgCgCQgEgCgDAAQgFAAgFAEQgEAEgBALIAAAeIgJAAIAAg4IAIAAIAAAIQAHgJAKAAQAGAAAEACQAFACACADIACAHIABAJIAAAig");
        this.shape_42.setTransform(162.2, 10.4);
        this.shape_43 = new cjs.Shape();
        this.shape_43.graphics.f("#A2DAFF").s().p("AgSAWQgIgHAAgPQAAgPAJgHQAIgHAJAAQAMAAAHAIQAIAIAAANQAAAKgDAGQgEAHgGADQgGAEgIAAQgLAAgHgIgAgLgQQgFAGAAAKQAAALAFAFQAFAGAGAAQAHAAAFgGQAFgFAAgLQAAgKgFgGQgFgFgHAAQgGAAgFAFg");
        this.shape_43.setTransform(155.1, 10.5);
        this.shape_44 = new cjs.Shape();
        this.shape_44.graphics.f("#A2DAFF").s().p("AgEAFIAAgKIAKAAIAAAKg");
        this.shape_44.setTransform(149.6, 12.8);
        this.shape_45 = new cjs.Shape();
        this.shape_45.graphics.f("#A2DAFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAKggIAIAAIAJAgIACALIAEgLIAKggIAJAAIgSA3g");
        this.shape_45.setTransform(143, 10.5);
        this.shape_46 = new cjs.Shape();
        this.shape_46.graphics.f("#A2DAFF").s().p("AALAcIgJggIgCgLIgKArIgKAAIgSg3IAKAAIAJAgIADALIADgLIAJggIAJAAIAJAgIADALIADgLIAJggIAKAAIgSA3g");
        this.shape_46.setTransform(134.1, 10.5);
        this.shape_47 = new cjs.Shape();
        this.shape_47.graphics.f("#A2DAFF").s().p("AALAcIgJggIgCgLIgLArIgKAAIgRg3IAKAAIAJAgIAEALIACgLIAKggIAIAAIAJAgIACALIAEgLIAKggIAJAAIgSA3g");
        this.shape_47.setTransform(125.1, 10.5);
        this.shape_48 = new cjs.Shape();
        this.shape_48.graphics.f("#A2DAFF").s().p("A7VBYIAAivMA2rAAAIAACvg");
        this.shape_48.setTransform(176, 9.8);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_23 }, { t: this.shape_22 }, { t: this.shape_21 }, { t: this.shape_20 }, { t: this.shape_19 }, { t: this.shape_18 }, { t: this.shape_17 }, { t: this.shape_16 }, { t: this.shape_15 }, { t: this.shape_14 }, { t: this.shape_13 }, { t: this.shape_12 }, { t: this.shape_11 }, { t: this.shape_10 }, { t: this.shape_9 }, { t: this.shape_8 }, { t: this.shape_7 }, { t: this.shape_6 }, { t: this.shape_5 }, { t: this.shape_4 }, { t: this.shape_3 }, { t: this.shape_2 }, { t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_47 }, { t: this.shape_46 }, { t: this.shape_45 }, { t: this.shape_44 }, { t: this.shape_43 }, { t: this.shape_42 }, { t: this.shape_41 }, { t: this.shape_40 }, { t: this.shape_39 }, { t: this.shape_38 }, { t: this.shape_37 }, { t: this.shape_36 }, { t: this.shape_35 }, { t: this.shape_34 }, { t: this.shape_33 }, { t: this.shape_32 }, { t: this.shape_31 }, { t: this.shape_30 }, { t: this.shape_29 }, { t: this.shape_28 }, { t: this.shape_27 }, { t: this.shape_26 }, { t: this.shape_25 }, { t: this.shape_24 }] }, 1).to({ state: [{ t: this.shape_48 }] }, 2).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(0, 1.5, 399.5, 16.2);
    p.frameBounds = [rect, rect, rect, new cjs.Rectangle(1, 1, 350, 17.5)];
    (lib.grc_screen = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.frame_0 = function() { this.stop(); }
        this.frame_18 = function() { this.gotoAndPlay(1); }
        this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(18).call(this.frame_18).wait(1));
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("AeFjWIAAGtQAACwitAEMg2oAAAQi0AAAAi0IAAmtQAAi0C0AAMA2oAAAQCtAEAACwg");
        this.shape.setTransform(192.5, 39.5);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.f("#E6E9FF").s().p("A7QGLQizAAgBi0IAAmtQABi0CzAAMA2oAAAQCtAEAACwIAAGtQAACwitAEg");
        this.shape_1.setTransform(192.5, 39.5);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.f("#F9757A").s().p("A7QGLQizAAgBi0IAAmtQABi0CzAAMA2oAAAQCtAEAACwIAAGtQAACwitAEg");
        this.shape_2.setTransform(192.5, 39.5);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_2 }, { t: this.shape }] }, 1).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }, 8).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }, 9).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 387.9, 82);
    p.frameBounds = [rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect];
    (lib.grc_scr_size = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f("rgba(0,51,204,0.008)").s().p("A/PRMMAAAgiXMA+fAAAMAAAAiXg");
        this.shape.setTransform(200, 110);
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(0, 0, 400, 220);
    p.frameBounds = [rect];
    (lib.grc_blue_bars = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#003399").s().p("A/PRMIAAjIMA+fAAAIAADIgA/PuDIAAjIMA+fAAAIAADIg");
        this.shape.setTransform(200, 110);
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(0, 0, 400, 220);
    p.frameBounds = [rect];
    (lib.grc_back = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#00FF00").s().p("AgLAyIgzgqIAAAAIgBAAIAAgBIAAAAQgEgDAAgDIAAgBQAAgEAEgCIA0grQACgBADgBQAEAAACACQACADAAADIAAARIA4gIQAEAAADACQADADgBADIAAA1QABADgDACQgDADgEAAIg4gIIAAARQAAADgCACQgCADgEAAQgDAAgCgCg");
        this.shape.setTransform(10.6, 9.3);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.f("#B9FE8B").s().p("AgLAyIgzgqIAAAAIgBAAIAAgBIAAAAQgEgDAAgDIAAgBQAAgEAEgCIA0grQACgBADgBQAEAAACACQACADAAADIAAARIA4gIQAEAAADACQADADgBADIAAA1QABADgDACQgDADgEAAIg4gIIAAARQAAADgCACQgCADgEAAQgDAAgCgCg");
        this.shape_1.setTransform(10.6, 9.3);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.f("rgba(0,51,153,0.008)").s().p("AvnBaIAAizIfPAAIAACzgAuJguIg1ArQgDACAAAEIAAABQAAADADADIAAAAIAAABIABAAIAAAAIA0AqQACACADAAQADAAADgDQACgCAAgDIAAgRIA5AIQADAAADgDQADgCAAgDIAAg1QAAgDgDgDQgDgCgDAAIg5AIIAAgRQAAgDgCgDQgDgCgDAAQgDABgCABg");
        this.shape_2.setTransform(100, 9);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape }] }).to({ state: [{ t: this.shape_1 }] }, 1).to({ state: [{ t: this.shape_1 }] }, 1).to({ state: [{ t: this.shape_1 }, { t: this.shape_2 }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(3.8, 4.2, 13.5, 10.3);
    p.frameBounds = [rect, rect, rect, new cjs.Rectangle(0, 0, 200, 18)];
    (lib.grc_stop = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.frame_0 = function() { this.stop(); }
        this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("ALODUIAAmnQAAhFhFAAI0RAAQhFAAAABFIAAGnQAABFBFAAIURAAQBFAAAAhFg");
        this.shape.setTransform(71.8, 28.1);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.lf(["#FF0000", "#FF0000"], [0, 1], 0, -26.9, 0, 27).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_1.setTransform(71.8, 28.1);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#FF0000", "#CC0000"], [0, 1], 0, -26.9, 0, 27).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_2.setTransform(71.8, 28.1);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_2 }, { t: this.shape }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 146.6, 59.2);
    p.frameBounds = [rect, rect];
    (lib.grc_start = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.frame_0 = function() { this.stop(); }
        this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("ALODUIAAmnQAAhFhFAAI0RAAQhFAAAABFIAAGnQAABFBFAAIURAAQBFAAAAhFg");
        this.shape.setTransform(71.8, 28.1);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.lf(["#00FF00", "#00CC00"], [0, 1], 0, -28, 0, 28.1).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_1.setTransform(71.8, 28.1);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.f().s("#303030").ss(3, 1, 1).p("ArNjTIAAGnQAABFBFAAIURAAQBFAAAAhFIAAmnQAAhFhFAAI0RAAQhFAAAABFg");
        this.shape_2.setTransform(71.8, 28.1);
        this.shape_3 = new cjs.Shape();
        this.shape_3.graphics.lf(["#00FF00", "#00CC00"], [0, 1], 0, -27, 0, 27).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_3.setTransform(71.8, 28.1);
        this.shape_4 = new cjs.Shape();
        this.shape_4.graphics.lf(["#00FFFF", "#0000FF"], [0, 1], 0, -26.5, 0, 26.6).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_4.setTransform(71.8, 28.1);
        this.shape_5 = new cjs.Shape();
        this.shape_5.graphics.lf(["#0000FF", "#00FFFF"], [0, 1], 0, -27, 0, 27).s().p("AqIEZQhFAAAAhFIAAmnQAAhFBFAAIURAAQBFAAAABFIAAGnQAABFhFAAg");
        this.shape_5.setTransform(71.8, 28.1);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_3 }, { t: this.shape_2 }] }, 1).to({ state: [{ t: this.shape_4 }, { t: this.shape }] }, 1).to({ state: [{ t: this.shape_5 }, { t: this.shape }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 146.6, 59.2);
    p.frameBounds = [rect, rect, rect, rect];
    (lib.grc_set = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("AHeBoIAAjPQAAgygyAAItXAAQgyAAAAAyIAADPQAAAyAyAAINXAAQAyAAAAgyg");
        this.shape.setTransform(47.8, 15.4);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.lf(["#00FF00", "#00CC00"], [0, 1], 0.1, -15, 0.1, 15.1).s().p("AmrCaQgyAAAAgyIAAjPQAAgyAyAAINXAAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_1.setTransform(47.8, 15.4);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#00CC00", "#00FF00"], [0, 1], 0.1, -15, 0.1, 15.1).s().p("AmrCaQgyAAAAgyIAAjPQAAgyAyAAINXAAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_2.setTransform(47.8, 15.4);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_2 }, { t: this.shape }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 98.6, 33.8);
    p.frameBounds = [rect, rect];
    (lib.grc_num = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("ADvBoIAAjPQAAgygyAAIl5AAQgyAAAAAyIAADPQAAAyAyAAIF5AAQAyAAAAgyg");
        this.shape.setTransform(23.9, 15.4);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.lf(["#00FF00", "#00CC00"], [0, 1], 0, -13.3, 0, 13.3).s().p("Ai8CaQgyAAAAgyIAAjPQAAgyAyAAIF5AAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_1.setTransform(23.9, 15.4);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#00CC00", "#00FF00"], [0, 1], 0, -13.3, 0, 13.3).s().p("Ai8CaQgyAAAAgyIAAjPQAAgyAyAAIF5AAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_2.setTransform(23.9, 15.4);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_2 }, { t: this.shape }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 50.9, 33.8);
    p.frameBounds = [rect, rect];
    (lib.grc_clear = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#303030").ss(3, 1, 1).p("AHehnIAADPQAAAygyAAItXAAQgyAAAAgyIAAjPQAAgyAyAAINXAAQAyAAAAAyg");
        this.shape.setTransform(47.8, 15.4);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.lf(["#CCCCCC", "#999999"], [0, 1], 0.1, -15.6, 0.1, 15.7).s().p("AmrCaQgyAAAAgyIAAjPQAAgyAyAAINXAAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_1.setTransform(47.8, 15.4);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#999999", "#CCCCCC"], [0, 0.925], 0.1, -15.6, 0.1, 15.7).s().p("AmrCaQgyAAAAgyIAAjPQAAgyAyAAINXAAQAyAAAAAyIAADPQAAAygyAAg");
        this.shape_2.setTransform(47.8, 15.4);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_1 }, { t: this.shape }] }).to({ state: [{ t: this.shape_2 }, { t: this.shape }] }, 1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, -1.5, 98.6, 33.8);
    p.frameBounds = [rect, rect];
    (lib.redArrow = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#333333").ss(3, 1, 1).p("AD1nlQgRgVgZAAImVAAQgZAAgSAVQgRAUAAAdIA9GmIiBAAQgXAAgQATQgRATAAAbQAAAXALARIFFGLQAUAVAcAAQACAAAAAAQACAAABAAQAdAAATgVIACgCQABgBABgBIABgBQABgCAAAAIABAAQABgCADgDIE5l/QAMgRAAgXQAAgbgRgTQgRgTgXAAIiAAAIA+mmQAAgdgTgUg");
        this.shape.setTransform(38.7, 51.9);
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.rf(["rgba(255,255,255,0.498)", "rgba(255,255,255,0.086)"], [0, 1], 20, -17.2, 0, 20, -17.2, 92.7).s().p("AhQhGIAAglIAAmfIBaAAQAaAAATAWQARAVABAdIhAG0ICEAAQAZAAARATQAQAUABAcQAAAYgMASIlOGWIg0AWQB2kaAAk3g");
        this.shape_1.setTransform(56.9, 52.3);
        this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#02FD34", "#84FB9B"], [0, 1], -37.3, -23.3, 40, -23.3).s().p("AglD9IlEmKIgCgDIADAEIFEGJQAKAKALAFQgMgFgKgKgAk8j3ICBAAIgDgUIADAVIiAAAQgYgBgQAUQAQgUAXAAgAFYj2IiAAAIAAgBIB/AAQALAAAKAEQgJgDgLAAg");
        this.shape_2.setTransform(37.3, 75.2);
        this.shape_3 = new cjs.Shape();
        this.shape_3.graphics.lf(["#FF0000", "#FE8181"], [0, 1], -38.6, 0, 38.7, 0).s().p("AAGH7IgBAAIgBAAIAAAAIgBAAIgDAAIAAAAIgCAAIgBAAIgagGQgLgFgKgKIlEmKIgDgEIgCgFIgHgeIAAgCQAAgbARgTQAQgSAYAAICAAAIgDgVIg7mSQABgdARgUIAAAAIABgCQAJgJAKgFQALgFAMAAIGVAAQAZAAASAVQARAUABAdIg+GmIAAABICAAAQALAAAJAEIAGADQAHAEAHAHQARATAAAbQAAAYgMARIk6F+IgDAFIgBABIgBABIgBACIgCACIgCABQgHAHgIAFIgdAJIgBAAg");
        this.shape_3.setTransform(38.7, 51.9);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape_3 }, { t: this.shape_2 }] }).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.4, -0.2, 80.3, 104.8);
    p.frameBounds = [rect];
    (lib.greenArrow = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.shape = new cjs.Shape();
        this.shape.graphics.f().s("#333333").ss(3, 1, 1).p("AF4haIlFmLQgUgVgbAAQgDAAgBAAQAAAAgCAAQgcAAgUAVIgCACQgBABAAABIgBABQgBACgBAAIgBAAQgBACgCADIk5F/QgNARAAAXQAAAbASAUQAQASAYAAIB/AAIg+GmQAAAdATAUQARAVAZAAIGVAAQAZAAASgVQARgUABgdIg+mmICBAAQAXAAAQgSQARgUAAgbQAAgXgLgRg");
        this.shape.setTransform(38.7, 52.7);
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.rf(["rgba(255,255,255,0.498)", "rgba(255,255,255,0.086)"], [0, 1], -19.9, 17.3, 0, -19.9, 17.3, 92.7).s().p("AgJILQgaAAgSgWQgTgVABgdIA/m0IiFAAQgXAAgSgTQgQgUAAgcQgBgYAMgSIFNmWIA2gWQh3EaAAE3IABAlIAAGfg");
        this.shape_1.setTransform(20.5, 52.3);
        this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.lf(["#02FD34", "#84FB9B"], [0, 1], 38.7, 0, -38.6, 0).s().p("AjKH7QgYAAgSgVQgSgUAAgdIA+mmIiBAAQgXAAgQgSQgRgTgBgcQAAgXAMgSIE5l+IAEgFIABAAIACgCIABgBIABgCIACgCQATgVAdAAIACAAIADAAQAcAAAVAVIFEGKQAKASABAXQAAAcgRATQgQASgXAAIiBAAIA9GmQAAAdgRAUQgSAVgZAAg");
        this.shape_2.setTransform(38.7, 52.7);
        this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-1.5, 0, 80.3, 104.8);
    p.frameBounds = [rect];
    (lib.scr_timer = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.txt_mils = new cjs.Text("000", "13px 'Arial'");
        this.txt_mils.name = "txt_mils";
        this.txt_mils.textAlign = "center";
        this.txt_mils.lineHeight = 15;
        this.txt_mils.lineWidth = 29;
        this.txt_mils.parent = this;
        this.txt_mils.setTransform(332.7, 93.5);
        this.txt_timer = new cjs.Text("00:00:00", "74px 'Arial'");
        this.txt_timer.name = "txt_timer";
        this.txt_timer.textAlign = "center";
        this.txt_timer.lineHeight = 83;
        this.txt_timer.lineWidth = 378;
        this.txt_timer.parent = this;
        this.txt_timer.setTransform(200.1, 25);
        this.txt_clear = new cjs.Text("Clear", "22px 'Arial'");
        this.txt_clear.name = "txt_clear";
        this.txt_clear.textAlign = "center";
        this.txt_clear.lineHeight = 25;
        this.txt_clear.lineWidth = 138;
        this.txt_clear.parent = this;
        this.txt_clear.setTransform(308.6, 140);
        this.txt_start = new cjs.Text("Start", "22px 'Arial'");
        this.txt_start.name = "txt_start";
        this.txt_start.textAlign = "center";
        this.txt_start.lineHeight = 25;
        this.txt_start.lineWidth = 138;
        this.txt_start.parent = this;
        this.txt_start.setTransform(94.2, 140);
        this.txt_back = new cjs.Text("Back", "12px 'Arial'", "#FFFFFF");
        this.txt_back.name = "txt_back";
        this.txt_back.lineHeight = 14;
        this.txt_back.lineWidth = 171;
        this.txt_back.parent = this;
        this.txt_back.setTransform(22.7, 202.5);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.txt_back }, { t: this.txt_start }, { t: this.txt_clear }, { t: this.txt_timer }, { t: this.txt_mils }] }).wait(1));
        this.btn_back = new lib.grc_back();
        this.btn_back.name = "btn_back";
        this.btn_back.parent = this;
        this.btn_back.setTransform(62.2, 217.6, 1, 1, 0, 0, 0, 62, 16.5);
        new cjs.ButtonHelper(this.btn_back, 0, 1, 2, false, new lib.grc_back(), 3);
        this.timeline.addTween(cjs.Tween.get(this.btn_back).wait(1));
        this.grc_clear = new lib.grc_stop();
        this.grc_clear.name = "grc_clear";
        this.grc_clear.parent = this;
        this.grc_clear.setTransform(308, 152.5, 1, 1, 0, 0, 0, 71.8, 28.1);
        this.grc_start = new lib.grc_start();
        this.grc_start.name = "grc_start";
        this.grc_start.parent = this;
        this.grc_start.setTransform(93, 152.5, 1, 1, 0, 0, 0, 71.8, 28.1);
        this.animatedObject = new lib.grc_screen();
        this.animatedObject.name = "animatedObject";
        this.animatedObject.parent = this;
        this.animatedObject.setTransform(199.7, 69.5, 1, 1, 0, 0, 0, 192.5, 39.5);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.animatedObject }, { t: this.grc_start }, { t: this.grc_clear }] }).wait(1));
        this.instance = new lib.grc_scr_size("synched", 0);
        this.instance.parent = this;
        this.instance.setTransform(200, 110, 1, 1, 0, 0, 0, 200, 110);
        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));
    }).prototype = getMCSymbolPrototype(lib.scr_timer, rect = new cjs.Rectangle(0, 0, 400, 220), [rect]);
    (lib.scr_set = function(mode, startPosition, loop) {
        if (loop == null) { loop = false; }
        this.initialize(mode, startPosition, loop, {});
        this.txt_set = new cjs.Text("Set", "22px 'Arial'");
        this.txt_set.name = "txt_set";
        this.txt_set.textAlign = "center";
        this.txt_set.lineHeight = 25;
        this.txt_set.lineWidth = 87;
        this.txt_set.parent = this;
        this.txt_set.setTransform(345.4, 125.3);
        this.txt_clear = new cjs.Text("Clear", "22px 'Arial'");
        this.txt_clear.name = "txt_clear";
        this.txt_clear.textAlign = "center";
        this.txt_clear.lineHeight = 25;
        this.txt_clear.lineWidth = 87;
        this.txt_clear.parent = this;
        this.txt_clear.setTransform(345.4, 164.3);
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#000000").s().p("AgiBGQgLgKgDgTIATgBQACANAHAGQAHAGAKAAQAIAAAHgFQAGgEAFgGQAEgHADgMQADgLAAgNIAAgDQgGAJgKAGQgKAFgLAAQgUAAgNgOQgOgNAAgXQAAgYAPgPQAOgOAVAAQAOAAANAIQANAIAGAQQAHAPAAAdQAAAdgHASQgGASgNAJQgNAJgQAAQgTAAgMgKgAgVg1QgKALAAAQQAAAPAJAKQAJAIANAAQANAAAJgIQAIgKAAgQQAAgRgIgKQgJgJgNAAQgMAAgJAKg");
        this.shape.setTransform(264.3, 137.4);
        this.shape_1 = new cjs.Shape();
        this.shape_1.graphics.f("#000000").s().p("AglBDQgOgOAAgVQAAgPAIgKQAIgKAOgEQgMgEgGgIQgFgIAAgMQAAgRAMgMQAMgLAUAAQAUAAANAMQAMAMAAARQAAALgFAIQgGAIgMAEQAPAFAHAKQAIAKAAAPQAAAUgOAOQgPANgXAAQgWAAgPgNgAgWAKQgJAJAAANQAAAJAEAHQAEAIAIAEQAHAFAIAAQAOAAAJgJQAJgJAAgOQAAgOgJgJQgJgJgOAAQgNAAgJAJgAgRg4QgIAHAAAKQAAALAHAHQAIAHAKAAQALAAAIgHQAHgHAAgKQAAgLgIgHQgHgHgLAAQgKAAgHAHg");
        this.shape_1.setTransform(206.3, 137.4);
        this.shape_2 = new cjs.Shape();
        this.shape_2.graphics.f("#000000").s().p("AgcBOQABgTAGgaQAHgaANgYQANgYAOgRIhMAAIAAgTIBlAAIAAAPQgPAQgPAbQgPAZgHAcQgGAUgBAYg");
        this.shape_2.setTransform(148.4, 137.4);
        this.shape_3 = new cjs.Shape();
        this.shape_3.graphics.f("#000000").s().p("AgkA/QgPgSAAgpQAAgtARgUQAOgSAYAAQATAAAMAKQAMAKACATIgUABQgCgLgFgFQgHgIgMAAQgIAAgHAFQgKAGgEANQgGANAAAYQAHgLAKgFQAKgFAKAAQATAAAOAOQAOANAAAXQAAAOgGANQgHANgLAHQgLAGgPAAQgXAAgPgRgAgUACQgJAJAAAQQAAAKAFAJQADAJAIAFQAHAFAIAAQAMAAAJgKQAJgKAAgRQAAgRgJgJQgIgIgOAAQgLAAgKAIg");
        this.shape_3.setTransform(90.3, 137.4);
        this.shape_4 = new cjs.Shape();
        this.shape_4.graphics.f("#000000").s().p("AgkBDQgNgMgCgUIAUgCQACAPAJAIQAIAIALgBQANAAAKgKQAKgLAAgRQAAgRgJgJQgKgJgOAAQgJAAgIAFQgHADgFAHIgSgDIAQhQIBNAAIAAATIg+AAIgIAqQAOgKAOAAQAVAAAOAPQAOANAAAWQAAAWgMAPQgPATgaAAQgVAAgOgMg");
        this.shape_4.setTransform(32.4, 137.5);
        this.shape_5 = new cjs.Shape();
        this.shape_5.graphics.f("#000000").s().p("AAOBPIAAgmIhDAAIAAgSIBGhlIAQAAIAABlIAVAAIAAASIgVAAIAAAmgAgiAXIAwAAIAAhGg");
        this.shape_5.setTransform(264, 176.3);
        this.shape_6 = new cjs.Shape();
        this.shape_6.graphics.f("#000000").s().p("AgjBEQgOgNgCgTIAUgDQADARAIAHQAIAIAMAAQAMAAAKgKQAJgKAAgNQAAgOgJgIQgIgJgOAAQgEAAgIACIACgQIADAAQALAAAKgHQAKgFAAgOQAAgLgHgHQgHgGgLgBQgLABgIAGQgHAIgCANIgUgDQAEgTANgLQAMgLATABQAMgBALAGQAKAGAGAJQAGAJAAALQAAALgGAIQgFAIgLAFQAOADAIAJQAIALAAAPQAAAVgPAOQgPAOgWAAQgVAAgOgMg");
        this.shape_6.setTransform(206.3, 176.4);
        this.shape_7 = new cjs.Shape();
        this.shape_7.graphics.f("#000000").s().p("AgzBPQAAgHACgHQAEgKAJgKQAJgKAQgOQAZgVAJgMQAJgMAAgLQAAgMgIgHQgJgIgNAAQgNAAgIAJQgIAHgBAPIgTgCQACgWANgMQANgLAWAAQAWAAAOAMQANANAAATQAAAJgEAJQgEAJgJAJQgJAKgVASQgQAOgFAGQgFAFgDAGIBMAAIAAASg");
        this.shape_7.setTransform(148.1, 176.3);
        this.shape_8 = new cjs.Shape();
        this.shape_8.graphics.f("#000000").s().p("AAKBPIAAh6QgIAGgJAHQgMAHgJADIAAgTQAQgHAMgLQALgLAFgKIANAAIAACdg");
        this.shape_8.setTransform(89.6, 176.3);
        this.shape_9 = new cjs.Shape();
        this.shape_9.graphics.f("#000000").s().p("AgjBAQgPgUAAgsQAAgbAFgRQAGgRALgJQAMgJAQAAQANAAAJAFQAKAFAGAJQAGAKAEAOQADAOAAAWQABAcgHARQgFARgLAJQgMAJgRAAQgWAAgNgQgAgVg0QgKAOABAmQgBAnAKANQAJANAMAAQANAAAKgNQAJgNAAgnQAAgmgJgNQgKgMgNAAQgMAAgJALg");
        this.shape_9.setTransform(32.3, 176.4);
        this.txt_mils = new cjs.Text("000", "13px 'Arial'");
        this.txt_mils.name = "txt_mils";
        this.txt_mils.textAlign = "center";
        this.txt_mils.lineHeight = 15;
        this.txt_mils.lineWidth = 29;
        this.txt_mils.parent = this;
        this.txt_mils.setTransform(332.7, 93.5);
        this.txt_timer = new cjs.Text("00:00:00", "74px 'Arial'");
        this.txt_timer.name = "txt_timer";
        this.txt_timer.textAlign = "center";
        this.txt_timer.lineHeight = 83;
        this.txt_timer.lineWidth = 378;
        this.txt_timer.parent = this;
        this.txt_timer.setTransform(200.1, 25);
        this.txt_back = new cjs.Text("Back", "12px 'Arial'", "#FFFFFF");
        this.txt_back.name = "txt_back";
        this.txt_back.lineHeight = 14;
        this.txt_back.lineWidth = 171;
        this.txt_back.parent = this;
        this.txt_back.setTransform(22.7, 202.5);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.txt_back }, { t: this.txt_timer }, { t: this.txt_mils }, { t: this.shape_9 }, { t: this.shape_8 }, { t: this.shape_7 }, { t: this.shape_6 }, { t: this.shape_5 }, { t: this.shape_4 }, { t: this.shape_3 }, { t: this.shape_2 }, { t: this.shape_1 }, { t: this.shape }, { t: this.txt_clear }, { t: this.txt_set }] }).wait(1));
        this.btn_back = new lib.grc_back();
        this.btn_back.name = "btn_back";
        this.btn_back.parent = this;
        this.btn_back.setTransform(62.2, 217.6, 1, 1, 0, 0, 0, 62, 16.5);
        new cjs.ButtonHelper(this.btn_back, 0, 1, 2, false, new lib.grc_back(), 3);
        this.timeline.addTween(cjs.Tween.get(this.btn_back).wait(1));
        this.grc_set = new lib.grc_set();
        this.grc_set.name = "grc_set";
        this.grc_set.parent = this;
        this.grc_set.setTransform(298.1, 121);
        new cjs.ButtonHelper(this.grc_set, 0, 1, 1);
        this.grc_clear = new lib.grc_clear();
        this.grc_clear.name = "grc_clear";
        this.grc_clear.parent = this;
        this.grc_clear.setTransform(322, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_clear, 0, 1, 1);
        this.grc_b4 = new lib.grc_num();
        this.grc_b4.name = "grc_b4";
        this.grc_b4.parent = this;
        this.grc_b4.setTransform(264.1, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b4, 0, 1, 1);
        this.grc_b3 = new lib.grc_num();
        this.grc_b3.name = "grc_b3";
        this.grc_b3.parent = this;
        this.grc_b3.setTransform(206.3, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b3, 0, 1, 1);
        this.grc_b2 = new lib.grc_num();
        this.grc_b2.name = "grc_b2";
        this.grc_b2.parent = this;
        this.grc_b2.setTransform(148.4, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b2, 0, 1, 1);
        this.grc_b1 = new lib.grc_num();
        this.grc_b1.name = "grc_b1";
        this.grc_b1.parent = this;
        this.grc_b1.setTransform(90.6, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b1, 0, 1, 1);
        this.grc_b0 = new lib.grc_num();
        this.grc_b0.name = "grc_b0";
        this.grc_b0.parent = this;
        this.grc_b0.setTransform(32.7, 176.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b0, 0, 1, 1);
        this.grc_b9 = new lib.grc_num();
        this.grc_b9.name = "grc_b9";
        this.grc_b9.parent = this;
        this.grc_b9.setTransform(264.1, 136.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b9, 0, 1, 1);
        this.grc_b8 = new lib.grc_num();
        this.grc_b8.name = "grc_b8";
        this.grc_b8.parent = this;
        this.grc_b8.setTransform(206.3, 136.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b8, 0, 1, 1);
        this.grc_b7 = new lib.grc_num();
        this.grc_b7.name = "grc_b7";
        this.grc_b7.parent = this;
        this.grc_b7.setTransform(148.4, 136.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b7, 0, 1, 1);
        this.grc_b6 = new lib.grc_num();
        this.grc_b6.name = "grc_b6";
        this.grc_b6.parent = this;
        this.grc_b6.setTransform(90.6, 136.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b6, 0, 1, 1);
        this.grc_b5 = new lib.grc_num();
        this.grc_b5.name = "grc_b5";
        this.grc_b5.parent = this;
        this.grc_b5.setTransform(32.7, 136.3, 1, 1, 0, 0, 0, 23.9, 15.3);
        new cjs.ButtonHelper(this.grc_b5, 0, 1, 1);
        this.animatedObject = new lib.grc_screen();
        this.animatedObject.name = "animatedObject";
        this.animatedObject.parent = this;
        this.animatedObject.setTransform(199.7, 69.5, 1, 1, 0, 0, 0, 192.5, 39.5);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.animatedObject }, { t: this.grc_b5 }, { t: this.grc_b6 }, { t: this.grc_b7 }, { t: this.grc_b8 }, { t: this.grc_b9 }, { t: this.grc_b0 }, { t: this.grc_b1 }, { t: this.grc_b2 }, { t: this.grc_b3 }, { t: this.grc_b4 }, { t: this.grc_clear }, { t: this.grc_set }] }).wait(1));
        this.instance = new lib.grc_scr_size("synched", 0);
        this.instance.parent = this;
        this.instance.setTransform(200, 110, 1, 1, 0, 0, 0, 200, 110);
        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));
    }).prototype = getMCSymbolPrototype(lib.scr_set, rect = new cjs.Rectangle(0, 0, 400, 220), [rect]);
    (lib.btn_stopwatch = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.instance = new lib.greenArrow("single", 0);
        this.instance.parent = this;
        this.instance.setTransform(98, 107.4, 1, 1, 0, 0, 0, 38.6, 52.4);
        this.timeline.addTween(cjs.Tween.get(this.instance).to({ _off: true }, 3).wait(1));
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#F0FBF2").s().p("AvYOEIAA8HIexAAIAAcHg");
        this.shape.setTransform(98.5, 90);
        this.shape._off = true;
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({ _off: false }, 0).wait(3));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(57.9, 55, 80.3, 104.8);
    p.frameBounds = [rect, rect = new cjs.Rectangle(0, 0, 197, 180), rect, rect];
    (lib.btn_countdown = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.instance = new lib.redArrow("single", 0);
        this.instance.parent = this;
        this.instance.setTransform(98, 107.4, 1, 1, 0, 0, 0, 38.6, 52.4);
        this.timeline.addTween(cjs.Tween.get(this.instance).to({ _off: true }, 3).wait(1));
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#F0FBF2").s().p("AvYOEIAA8HIexAAIAAcHg");
        this.shape.setTransform(98.5, 90);
        this.shape._off = true;
        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({ _off: false }, 0).wait(3));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(57.9, 54.8, 80.3, 104.8);
    p.frameBounds = [rect, rect = new cjs.Rectangle(0, 0, 197, 180), rect, rect];
    (lib.scr_menu = function(mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});
        this.txt_countdown = new cjs.Text("Countdown", "22px 'Arial'");
        this.txt_countdown.name = "txt_countdown";
        this.txt_countdown.textAlign = "center";
        this.txt_countdown.lineHeight = 25;
        this.txt_countdown.lineWidth = 192;
        this.txt_countdown.parent = this;
        this.txt_countdown.setTransform(301.3, 36);
        this.txt_stopwatch = new cjs.Text("Stopwatch", "22px 'Arial'");
        this.txt_stopwatch.name = "txt_stopwatch";
        this.txt_stopwatch.textAlign = "center";
        this.txt_stopwatch.lineHeight = 25;
        this.txt_stopwatch.lineWidth = 192;
        this.txt_stopwatch.parent = this;
        this.txt_stopwatch.setTransform(98.3, 36);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.txt_stopwatch }, { t: this.txt_countdown }] }).wait(1));
        this.btn_stopwatch = new lib.btn_stopwatch();
        this.btn_stopwatch.name = "btn_stopwatch";
        this.btn_stopwatch.parent = this;
        this.btn_stopwatch.setTransform(62, 36.5, 1, 1, 0, 0, 0, 62, 16.5);
        new cjs.ButtonHelper(this.btn_stopwatch, 0, 1, 2, false, new lib.btn_stopwatch(), 3);
        this.btn_countdown = new lib.btn_countdown();
        this.btn_countdown.name = "btn_countdown";
        this.btn_countdown.parent = this;
        this.btn_countdown.setTransform(264.8, 36.5, 1, 1, 0, 0, 0, 62, 16.5);
        new cjs.ButtonHelper(this.btn_countdown, 0, 1, 2, false, new lib.btn_countdown(), 3);
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#EEEEEE").s().p("AgeOEIAA8IIA9AAIAAcIg");
        this.shape.setTransform(200.2, 110.1);
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.shape }, { t: this.btn_countdown }, { t: this.btn_stopwatch }] }).wait(1));
    }).prototype = getMCSymbolPrototype(lib.scr_menu, rect = new cjs.Rectangle(0, 20, 399.8, 180.1), [rect]);
    (lib.index = function(mode, startPosition, loop) {
        if (loop == null) { loop = false; }
        this.initialize(mode, startPosition, loop, {});
        this.instance = new lib.sound();
        this.instance.parent = this;
        this.instance.setTransform(-89.9, 261.1);
        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));
        this.onlinestopwatch = new lib.onlinestopwatchcom();
        this.onlinestopwatch.name = "onlinestopwatch";
        this.onlinestopwatch.parent = this;
        this.onlinestopwatch.setTransform(80, 8.6, 1, 1, 0, 0, 0, 80, 8.6);
        new cjs.ButtonHelper(this.onlinestopwatch, 0, 1, 2, false, new lib.onlinestopwatchcom(), 3);
        this.timeline.addTween(cjs.Tween.get(this.onlinestopwatch).wait(1));
        this.src_menu = new lib.scr_menu();
        this.src_menu.name = "src_menu";
        this.src_menu.parent = this;
        this.scr_set = new lib.scr_set();
        this.scr_set.name = "scr_set";
        this.scr_set.parent = this;
        this.scr_set.setTransform(400, 0);
        this.scr_set.visible = false;
        this.scr_timer = new lib.scr_timer();
        this.scr_timer.name = "scr_timer";
        this.scr_timer.parent = this;
        this.scr_timer.setTransform(-400, 0);
        this.scr_timer.visible = false;
        this.timeline.addTween(cjs.Tween.get({}).to({ state: [{ t: this.scr_timer }, { t: this.scr_set }, { t: this.src_menu }] }).wait(1));
        this.instance_1 = new lib.grc_blue_bars("synched", 0);
        this.instance_1.parent = this;
        this.instance_1.setTransform(200, 110, 1, 1, 0, 0, 0, 200, 110);
        this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));
    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = rect = new cjs.Rectangle(-200, 110, 1200, 220);
    p.frameBounds = [rect];
    lib.properties = { id: '0BDF003865143E41B61E47B1C6F8B843', width: 400, height: 220, fps: 24, color: "#FFFFFF", opacity: 1.00, manifest: [{ src: "./sound/Alarm01.wav", id: "bell" }], preloads: [] };
    (lib.Stage = function(canvas) { createjs.Stage.call(this, canvas); }).prototype = p = new createjs.Stage();
    p.setAutoPlay = function(autoPlay) { this.tickEnabled = autoPlay; }
    p.play = function() {
        this.tickEnabled = true;
        this.getChildAt(0).gotoAndPlay(this.getTimelinePosition())
    }
    p.stop = function(ms) {
        if (ms) this.seek(ms);
        this.tickEnabled = false;
    }
    p.seek = function(ms) {
        this.tickEnabled = true;
        this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000);
    }
    p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }
    p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }
    an.bootcompsLoaded = an.bootcompsLoaded || [];
    if (!an.bootstrapListeners) { an.bootstrapListeners = []; }
    an.bootstrapCallback = function(fnCallback) { an.bootstrapListeners.push(fnCallback); if (an.bootcompsLoaded.length > 0) { for (var i = 0; i < an.bootcompsLoaded.length; ++i) { fnCallback(an.bootcompsLoaded[i]); } } };
    an.compositions = an.compositions || {};
    an.compositions['0BDF003865143E41B61E47B1C6F8B843'] = { getStage: function() { return exportRoot.getStage(); }, getLibrary: function() { return lib; }, getSpriteSheet: function() { return ss; }, getImages: function() { return img; } };
    an.compositionLoaded = function(id) { an.bootcompsLoaded.push(id); for (var j = 0; j < an.bootstrapListeners.length; j++) { an.bootstrapListeners[j](id); } }
    an.getComposition = function(id) { return an.compositions[id]; }
})(createjs = createjs || {}, AdobeAn = AdobeAn || {});
var createjs, AdobeAn;